version: "2"
services:
  db:
    image: postgres
    command:
      - -c
      - max_replication_slots=10
      - -c
      - wal_level=logical
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  openehr:
    image: "ehrbase/ehrbase:0.16.5"
    environment:
      ADMINAPI_ACTIVE: "true"
      ADMINAPI_ALLOWDELETEALL: "true"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/ehrbase"
      SPRING_DATASOURCE_USERNAME: ehrbase
      SPRING_DATASOURCE_PASSWORD: ehrbase
      SERVER_AQLCONFIG_USEJSQUERY: "false"
      SERVER_NODENAME: "localhost"
    depends_on:
      - db

  cypress:
    image: cypress
    build: .
    container_name: cypress
    command: sh -c "/wait && npm run ci"
    environment:
      WAIT_HOSTS: db:5432, openehr:8080
      WAIT_TIMEOUT: 300
      WAIT_AFTER: 5
      WAIT_SLEEP_INTERVAL: 5
    volumes:
      - ./template.opt:/app/template.opt
      - ./cypress:/app/cypress
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./index.html:/app/index.html
      - ./cypress.env.json:/app/cypress.env.json
      - ./cypress.json:/app/cypress.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.js:/app/vite.config.js
      - ./output:/app/mochawesome-report
    depends_on:
      - openehr
      - db
